$(function(){
    //候補を配列で設定
    var campers = [
      'ひーくん@carabiner.camp',
      'ぺりきゃん△@per1camp',
      '3本ノック@ハンモック好き@dekobopunch',
      'Toya@侍組@tanuu_rs2',
      '̥✼̥୭ ηαgi.͙✼̥୭@abd0852741',
      'yadamon@アパラチア護民隊@yada_in',
      'たけ△．還暦からの月一ソロキャン@take_solo_camp',
      '5hir0camp / しろきゃんぷ@x5hir0campx',
      'チカチーロ（しょうい。）リモートワーク中@ShunTheRainbow',
      'ジルコねん@jilko_jp',
      'NAGA@SnowWako',
      'Banchan@outdoorlife_117',
      'Tatuya Camp@binmomo1',
      'きねちゃん／キャンプ@kinecampman',
      'にがりん@関西キャンパー team｢はらっぱ｣@nigari_com',
      'まさ@masa_camper',
      '白黒ぱんだパンダの顔@panpasupand',
      'あおじる@bisco_bisco_bis',
      'けん@strongs24crew',
      'みやび@qzpUtNMZOsYlWr7',
      '☆Luna☆@Luna_camp_star',
      'M3-GPEC COC 【公式】@Gpecoc',
      'うぃるちん@キャンプLv13@will_I_am_55',
      'すべきゃん@All for camping@camping_for',
      'gaw.gaw ～T.G.H.～@GAW_samurai',
      'すずQ@SuzuQ_camp',
      'taru@ronmmo',
      '望○羽(MOVEcamping)@nonoha_taka',
      'ナナチ@キャンプ△@nanachi_camp',
      'ガンちゃん@RYOLAND6',
      'ろんちゃんねる【Camp Living Life】@ron_camplife',
      'N4SyO@スノーボードとキャンプ大好きマン@N4SyO',
      'みいハムスターの顔きゃんぷ初心者マークテント@miickan00',
      'のん@clowna1',
      '優人@yuuutoo0525',
      '現役中学生の釣り日記⸜(* ॑꒳ ॑* )⸝@turityuugakusei',
      '僕の飯@boku_no_messi',
      'ぐっさん△Goodsun@ashitahejump123',
      'むーす@moose_campai',
      'あゆみん【NIGINIGIキノコhandmade.】@YQHb8QxwJdA4XXI',
      'たかみな / キャンプ△@takamina_camp',
      'ルフィ@camp.co.jp@me83864984',
      'ぬっきー@nununununukkin',
      'Ｓの人@cb1000sf@wopp5005',
      'にけにこ@Nikenikoseikatu',
      '管理栄養士＊キャンプ　Atsuya@campingphoto1',
      '鶏ガラ△雑コラキャンパー@torigaraworks',
      '黄色のハートキャンパーMS🏕黄色のハート@campermyst',
      'のめしstyle@ソロキャン勢@style64086365',
      'けろっぺ@kerorin5050',
      'のっち@L3bOmKVyGsyOBIi',
      '☔ありさ🌧@hakidamenk',
      '楽しむタイム@tanoshimu_time',
      'いも野郎っ♪テントマイクロバス@charaikamoyo',
      'wat.camp@CanpWat',
      'METS(ﾒｯﾂ)@METS23722427',
      'Outdoor_Nomu@Outdoor_Nomu',
      'はぬり@hanuri_camp',
      'Kai 釣り好き@Ksseabass80',
      'ノニヤマ＠週末は山の人@_noniyama_',
      'おᒍᑌᑎ@malcaju_camp',
      'りょーきゃん【新潟キャンパー】@r_camping_photo',
      'マギー(孤高の旅人)🏕書籍ボウルとスプーン@mqhxx365',
      'カクテルグラスましゅカクテルグラスCampテント@yakimashumaronn',
      'TOMO@鉄板屋@tomoBBQ1',
      '腱【伊豆キャンプ場開拓】@izucamp',
      'ƈձოթ⚒Ꭹu☆彡@campyou88',
      '【BonFire】たっしーCAMぷ。@Bonfire001',
      'よちこウサギの顔△△△@yochiyochi___',
      'たぬき(元らいおん)@jimjimjimny',
      'とっぽ＠駆け出しキャンパーテント@legotoppo',
      'キャンプラバー🏕太陽の光虹☔@CAMP_LOVER1',
      'はちきゃん【ソロキャン】@Hachicam',
      'doppelganger@doppelganger1st',
      'ぞえきゃん@Tamaki_D',
      'じらふまにあ/giraffe_mania@giraffe_mania1',
      'ぱーる初心者マーク🏕@pearl1108aaaaa',
      'ぶさコマ(Myキャンプ場開拓中)@busa_koma',
      'しょうわの昭に、、、、@t2051821',
      'Kuro Campくろすけ black(黒)@kuro969nao',
      'ZIMA@ZIMA_family',
      'キャンプ先輩@KYOU9210',
      'やばお@月1キャンプ@medic0004',
      'AKICAMP（あきキャン。）@aki_camper',
      'ジョー@jo_camplife',
      'm.@nicopho',
      'Nao@Nao_famicampapa',
      'ピチピチ@ファミリーキャンプ@Pichipichi78',
      'メガネキャンプ@アウトドア好き@meganecamp',
      'NVさん@NV65495045',
      'ふんばり聖闘士@hunbari_saint',
      'オオニョ@oonyo036',
      'くろすけ@kurosukerou',
      'めっそん@dadandanmam',
      'たくや＊⛺@よーらキャンプしてみる@yora_camp',
      'ルル　キャンプ@KNyP9ZgrSfr2xNp',
      '村人その3@murabitosono33',
      'しゃこう@shako_field',
      'のりち@norichbutfun',
      'しむ@miruyyo',
      'cowcow®︎ウシ夜勤中顔つき上弦の月@cowcowma_n',
      'もつ@キャンプ初心者@PONpokmon',
      '味しな@ksuke37378864',
      'TAÅK@TAAK_photograph',
      'けだま@_fluffy_white_',
      'てち。キャンプ初心者初心者マーク@Teti_Camp',
      'はぶてぃん@habtin0809',
      'HiroKing（ひろきん）@BTiti169',
      'ZRX1200S@Yasube7531',
      'つぼFamテントキャンプ垢炎料理@2BOcanp',
      'ちゃむすけ@chumsuke_camp',
      'edy:育児とバスケと音楽と酒とキャンプが好きな男のつぶやき@edy_outdoorsite',
      'atsucamp@m_w_a_m08',
      'けんけん@58kenken',
      'アツ△ Lv 1キャンパー@Camper28820497',
      'ミッチー山@my20100710yy',
      'さとし@sts_kzm',
      'ふうきゃん@FuCamp8',
      '3minutesRocketsテント@3minutesRockets',
      'Gyoro@Gyoro20',
      'とおる@初心者キャンパー@106chan6',
      'Wakky_love_dod_camp@Wakky_Camp',
      'ぬこ。@panco_Rea',
      'スバクCampスイカ@subak_camp',
      'ももにく太郎@mo_mo_ni_ku',
      'michi@micchiip',
      'furasan@人見知りキャンパー@furasan_',
      '釣りキチたけやん@turikichi0522',
      'ヘースケjimcamfish76@jimcamfish76',
      'ノリウェー@noriway13',
      'Rehealth@Rehealth_M',
      'フラットボーイ@deliboy0058',
      'ぶるもりΔ@Bluemoris0611',
      'DALY”ダリィ”＠アウトランダーPHEV使い@DALYs_Studio',
      'かつ@6TwQhS4eFn1BFHA',
      'Kaji@Kaji09291227',
      'snow@unagiinuuuu0605',
      '新町@shinmachi_fukui',
      'HICK CAMP@CampHick',
      'AKI@jeepcamper_mw3',
      'Sちゃん@yabe310',
      'sawazo@sawazo0308',
      '⊠あゃ🏕 ⊠@yopichan1029',
      'キャンプ大好きん@Akitainu228326',
      '海狸-kairi-@キャンプ垢テント@kairi_camp',
      '赤いリンゴ佐藤さん家のえんちゃんイヌ@enchan0810__',
      // 'RIKO@初心者デイキャンパー初心者マーク@Riko_syosinsya',
      '中学生キャンパー@yokosuk02023947',
      'みか✲毎日釣りしたい@mikapo15',
      '土の塊@tsuchi_katamari',
      'ゆじろっく@yujirock1981',
      '禽ӫデイキャンプしてきたよ@05rap_tori_al14',
      'ハイケミーテントYouTube配信中【公式】@Gaimon85',
      '麻理鈴@LOLODARIN',
      'Sputniks@Sputniks',
      '竜之介@tyaso4',
      'どくろべー@dokurobei_2000',
      'はらぺこ@初心者マークキャンパー@harapeko_camp',
      '✿神弥-DRUNK-@SHINYATTER',
      'ぶりざあど＠LE 遊炎ノ巣@dp_qb_dp_qb',
      '▷▶︎毛糸_ゆちゃん◀︎◁@queite_kt',
      'スナフキン@BVJTSMmQiV2nvIX',
      'ファスナー@fasuner',
      'mahiro@tnfget',
      '空白さん@キャンプ@d1j3RoxODqo0PKN',
      'jimcampapa@美脚キャンパー@jimcampapa',
      'iwashi△魚@iwashi01840184',
      '勇者ヘッドロココテントキャンプはドラクエ炎レベル1@kymk5511',
      'トトノイCAMP-HITOMOS灯ともす@totonoiathom',
      'たぴおかテント@TAPI_CAMP',
      'バヤちゃん| キャンプ系ビデオグラファー@baya60830',
      'ひろと湯のみｷｬﾝﾌﾟΔ@jbl9_mito24',
      '高橋ハム丸@yuuyuu0827',
      'のぶ@nobunobbe',
      'km@km36502',
      // 'やのCamp@Camp62yano',
      'えーくんウサギの顔高村瑛一⛺炎落葉樹@takamura0801',
      'syu☆camp@shinon_campfire',
      '長門@sotodenerudake',
      'ぐび兄@レベル9@amereo110410',
      'パパの村づくり100日間@30半ばサラリーマン@istorioa_oarai',
      'さかな@osakana_yys',
      '礼央@kyoumoganbaruzp',
      'Bun_jiijii_2020@Bun_Jiijii',
      '岡 武士　逆から読むと　シケた顔@Siketa_Kao',
      'コミ（新潟キャンパー）@KOMI_04733',
      'もふもふ@mofumofuwanko20',
      'ｳﾒｶﾞｷ@umechaan2',
      'マサ@masa_ska_',
      '【Bt愛チャンネル】DANGO@DANGO15799435',
      '🏕フラペチーノ　キャンプ🏕@kazu999furapeti',
      'さーくん=ゅぅご@satoru1209',
      'ひろさん『APACHE CAMP』@gotacamp',
      'アルテミス 軍幕群@Artemis4521',
      'np Camp⛺@np65144135',
      'イソログ@isolog0821',
      'ざわ39@zawa_norman',
      'かぼめめ@KABOCAMP',
      'プリーム@kouta06121',
      'corabo@corabo7',
      'なおつ@エリアトラウトどはまり@naotsu_1130',
      '目指せcamperアジアとオーストラリア@sakusakare',
      'イースト@eastbighelp',
      'しは犬@sihainu',
      '釣りおじさん△@fishing_ojisan8',
      '【ナルゾウ-naruzo-】風船ピエロの顔@naru_zo_camp',
      '看護師ピロリ@kangoshi_pirori',
      'mama@パイティアオchannel@my09892293',
      'お髭坊主@ohigeboz',
      '岡 武士　逆から読むと　シケた顔@Siketa_Kao',
      'ゆーじ＠なまけものキャンプ@yujiqo_op',
      'Shoji@one_up_manship'
      ];
    
    //グローバル変数
    var key = 0;
    var max_len = campers.length - 1;
    var randStart;
    var speed = 100; //シャッフルスピード
    
    //文字シャッフル関数
    //20ミリ秒毎に候補の文字列をシャッフルさせる
    var randShuffle= function(){
        if(key > max_len) key = 0;
        $('.rand_name').text(campers[key]);
        key++;
    }
    //文字シャッフル開始
    randStart = setInterval(randShuffle, speed);
    
    //回転を止める（抽選結果）
    $('.stop').click(function(){
        var random = Math.floor(Math.random() * (max_len + 1)); //ランダムで配列の数を取得
        $('.rand_name').text(campers[random]); //対象の数値に該当する文字を表示
        clearInterval(randStart); //シャッフルストップ
        $(this).hide(); //止めるボタンの非表示
        $('.restart').show(); //再開ボタンの表示
    });
    
    //回転を再開する
    $('.restart').click(function(){
        $(this).hide(); //再開ボタンの非表示
        $('.stop').show(); //止めるボタンの表示
        randStart = setInterval(randShuffle, speed); //シャッフル再開
    });
    
});